disabled_rules:
  - line_length
  - type_body_length
  - function_body_length
  - file_length
  - large_tuple
  - identifier_name
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - force_try
  - force_cast
excluded:
  - src/common/libmpdclient
