language: swift
osx_image: xcode9
script:
    - xcodebuild clean build -project Shinobu.xcodeproj -scheme shinobu-ios -destination "platform=iOS Simulator,name=iPhone 7,OS=12.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
