/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_HOST "localhost"

#define DEFAULT_PORT 6600

#define DEFAULT_SOCKET "/var/run/mpd/socket"

#define ENABLE_TCP 1

#define HAVE_GETADDRINFO 1

#define PACKAGE "libmpdclient"

#define VERSION "2.13"

